### ISSUE TITLE
[Request] cachyos-hardened

### ISSUE THREAD

**Issue by yavko** [chaotic-cx/nyx#146]
### Link to the package upstream website/repository

[cachyos-hardened](https://github.com/CachyOS/linux-cachyos/tree/master/linux-cachyos-hardened)

### Utility this package has for you

I like cachyos's scheduler, but I'd like to use hardened patches to keep my system secure

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Are you sure the package isn't available upstream already?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by PedroHLC** [comment]
Sorry for not replying yet, but we are looking for means for compiling more kernels (easy) and store them (hard, we'll probably need to ditch cachix)

**Comment by yavko** [comment]
> Sorry for not replying yet, but we are looking for means for compiling more kernels (easy) and store them (hard, we'll probably need to ditch cachix)

Ah, makes sense! Which cache are you considering?

**Comment by PedroHLC** [comment]
Next version bump, we'll merge linux_hdr with linux_cachyos, and a slot for this one will open.

**Comment by yavko** [comment]
> Next linux_cachyos bump, we'll merge linux_hdr with linux_cachyos, and a slot for this one will open.

Ah okay

**Comment by JustTNE** [comment]
@PedroHLC now that our storage issues are solved, is this something you want to investigate?

**Comment by PedroHLC** [comment]
> @PedroHLC now that our storage issues are solved, is this something you want to investigate?

I have to take a look at it to remove the IFD, I think I can take them both in one play!

**Comment by PedroHLC** [comment]
@yavko it's done, and cached, including modules, ZFS is pinned to cachy's tested revision, and earlier I removed the IFD.

**Comment by PedroHLC** [comment]
@yavko, @sirlucan archived it in https://github.com/CachyOS/linux-cachyos/commit/7fab8238805a91898554070712c09290d3d3c0e5 - should I drop it?
