### ISSUE TITLE
[Request] cosmic epoch desktop

### ISSUE THREAD

**Issue by rkunschke** [chaotic-cx/nyx#209]
### Link to the package upstream website/repository

https://github.com/pop-os/cosmic-epoch

### Utility this package has for you

I think cosmic epoch has a big potential, and I really want to try it out. I know it is available in the chaotic AUR as well.
But I know it is one bigger task, so I would understand if its to much work to implement all the necessary packages.
But there is some interest on packaging the cosmic desktop in the nixos community:
[https://github.com/NixOS/nixpkgs/issues/199563](https://github.com/NixOS/nixpkgs/issues/199563)
[https://www.reddit.com/r/NixOS/comments/ulugik/how_to_install_poposs_cosmic_desktop_environment/](https://www.reddit.com/r/NixOS/comments/ulugik/how_to_install_poposs_cosmic_desktop_environment/)
And other than that there is some work done already:
[https://github.com/pop-os/cosmic-comp/pull/53](https://github.com/pop-os/cosmic-comp/pull/53)

### Do you consider the package(s) to be useful for every Chaotic-Nyx user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Are you sure the package isn't available upstream already?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by PedroHLC** [comment]
This one we'll be interesting to add indeed, but needs some strategizing before doing it, so I'll need some time.

**Comment by rkunschke** [comment]
> This one we'll be interesting to add indeed, but needs some strategizing before doing it, so I'll need some time.

Great to hear that. Thank you :)

**Comment by Nyabinary** [comment]
https://github.com/NixOS/nixpkgs/pull/251365
 There's a PR open for Nixpkgs to add COSMIC, maybe we can do something like cosmic-git?

**Comment by PedroHLC** [comment]
> There's a PR open for Nixpkgs to add COSMIC,

That helps A LOT, and the author is great!

**Comment by PedroHLC** [comment]
UPDATE: Current stuck due to: https://github.com/chaotic-cx/nyx/issues/403

**Comment by PedroHLC** [comment]
Closing this, don't have time to do it myself, if someone is that much interested, please open a PR instead.
