### ISSUE TITLE
[Bug] Error when updating my chaotic inputs.

### ISSUE THREAD

**Issue by LudovicoPiero** [chaotic-cx/nyx#295]
### What happens?

When i run `nix flake lock --update-input chaotic` i got this error.

```
❯ nix flake lock --update-input chaotic 
error:
       … while updating the lock file of flake 'git+file:///home/ludovico/.config/nixos?ref=refs/heads/flake-parts&rev=9e5fcc961fc468cf35be1dffa038d768d42a596c'

       … while updating the flake input 'chaotic'

       … while updating the flake input 'chaotic/beautyline-icons-git-src'

       … while fetching the input 'gitlab:garuda-linux/themes-and-settings/artwork/beautyline'

       error: unable to download 'https://gitlab.com/api/v4/projects/garuda-linux%2Fthemes-and-settings/repository/commits?ref_name=artwork/beautyline': HTTP error 404

       response body:

       {"message":"404 Project Not Found"}
```

### What is expected to happen?

Chaotic should be updated without any errors.

### More information

My flake.nix is available [here](https://github.com/LudovicoPiero/dotfiles/blob/flake-parts/flake.nix)

**Comment by PedroHLC** [comment]
I don't have this issue, just tested, but that URL is indeed 404ing, Cc @dr460nf1r3.

**Comment by PedroHLC** [comment]
```console
╰─λ nix flake lock --update-input beautyline-icons-git-src -vv
...
downloading 'https://gitlab.com/api/v4/projects/garuda-linux%2Fthemes-and-settings%2Fartwork%2Fbeautyline/repository/commits?ref_name=HEAD'...
```

There is something really weird going on with your Nix. You see how the `ref_name` should be HEAD and in yours `%2Fartwork/beautyline` is missing in the base path?

I can see that in your `flake.lock` the last committed iteration had the correct entry...

**Comment by PedroHLC** [comment]
Cc @privatevoid-net, you might find this interesting...

**Comment by PedroHLC** [comment]
NOTE: This might not happen anymore since we moved all VCS packages' sources to use good-old fetchers.
