### ISSUE TITLE
[Request] libopenraw

### ISSUE THREAD

**Issue by Dreaming-Codes** [chaotic-cx/nyx#376]
### Link to the package upstream website/repository

https://libopenraw.freedesktop.org/
https://gitlab.freedesktop.org/libopenraw/libopenraw

### Utility this package has for you

It's needed to build tauri v2 appimages

### Do you consider the package(s) to be useful for every Chaotic-Nyx user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Are you sure the package isn't available upstream already?

- [x] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by PedroHLC** [comment]
I saw your PR at nixpkgs, and it looks almost ready to merge there.

Mind if instead I add a `libopenraw_git` here that updates daily from the latest commit in the master branch?

**Comment by Dreaming-Codes** [comment]
Sure, that's fine!

**Comment by PedroHLC** [comment]
UPDATE: Current stuck due to: https://github.com/chaotic-cx/nyx/issues/403
