### ISSUE TITLE
[Request] firefox-nightly-wayland

### ISSUE THREAD

**Issue by Nyabinary** [chaotic-cx/nyx#456]
### Link to the package upstream website/repository

N/A

### Utility this package has for you

Firefox but without x11 dependencies, so it's lighter :3

### Do you consider the package(s) to be useful for every Chaotic-Nyx user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Are you sure the package isn't available upstream already?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by PedroHLC** [comment]
Even though I'm an enthusiast about Wayland, I don't see any point in having something that will target less users while providing the exact same features/performance as the current wider option.

All the Wayland DEs pre-compiled in nixpkgs has XWayland enabled and brings all the XOrg deps with it.
