### ISSUE TITLE
[Request] linux-cachyos-rc

### ISSUE THREAD

**Issue by LudovicoPiero** [chaotic-cx/nyx#525]
### Link to the package upstream website/repository

https://github.com/CachyOS/linux-cachyos/tree/master/linux-cachyos-rc

### Utility this package has for you

It will be useful for those who want to test / try the linux-mainline version of cachyos.

### Do you consider the package(s) to be useful for every Chaotic-Nyx user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Are you sure the package isn't available upstream already?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by PedroHLC** [comment]
Closed in https://github.com/chaotic-cx/nyx/commit/f6c299e274ab1cd332fe2c78104f1bce21666e0c

Thank JohnRTitor

PS: Merged without caching kernel-modules due to complications in maintaining it.
