### ISSUE TITLE
Add instructions for non-NixOS home-manager users

### ISSUE THREAD

**Issue by bayazidbh** [chaotic-cx/nyx#54]
Hi, I still don't really get how to use flakes, I put in the flake configs in `~/.config/home-manager/flake.nix` and I got the following output:

```
warning: creating lock file '/home/fenglengshun/.config/home-manager/flake.lock'
error: flake 'path:/home/fenglengshun/.config/home-manager' does not provide attribute 'packages.x86_64-linux.homeConfigurations', 'legacyPackages.x86_64-linux.homeConfigurations' or 'homeConfigurations'
error: flake 'path:/home/fenglengshun/.config/home-manager' does not provide attribute 'packages.x86_64-linux.homeConfigurations', 'legacyPackages.x86_64-linux.homeConfigurations' or 'homeConfigurations'
error: flake 'path:/home/fenglengshun/.config/home-manager' does not provide attribute 'packages.x86_64-linux.homeConfigurations."fenglengshun".activationPackage', 'legacyPackages.x86_64-linux.homeConfigurations."fenglengshun".activationPackage' or 'homeConfigurations."fenglengshun".activationPackage'
```

Currently, I only understand using import \<channel\>, builtins.fetchTarball, and builtins.fetchGit. Could an example for home-manager flake config be added please? Or maybe a simpler import set-up that could be added to instructions?

**Comment by PedroHLC** [comment]
Currently, we don't have a home-manager-specific module. But the overlay should still work as desired:

1. Add the inputs to the `flake.nix`:
```diff
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
+    chaotic.url = "github:chaotic-cx/nyx/nyxpkgs-unstable";
  };
```

2. You still need to get the `chaotic` from the input attrset:
```diff
-  outputs = { nixpkgs, ... }: {
+  outputs = { nixpkgs, chaotic, ... }: {
```

3. Now you have to add our overlay to [home-manager's `nixpkgs.overlays`](https://nix-community.github.io/home-manager/options.html#opt-nixpkgs.overlays) option:
```diff
nixpkgs.overlays = [ chaotic.overlays.default ];
```

4. After this, you shall be able to install our packages as if they were from nixpkgs:
```diff
home.packages = with pkgs; [ yuzu-early-access_git ];
```

**Comment by PedroHLC** [comment]
@bayazidbh bumping you to know if it worked. (So I can add it to the README)

**Comment by bayazidbh** [comment]
Uh, I'm still very new to Nix, so I'm not entirely sure what I'm supposed to do, maybe an example of the whole `flakes.nix`? Otherwise, I'll try this out when I have the time this weekend. Sorry about that...

**Comment by PedroHLC** [comment]
I asked ChatGPT, I'm pretty sure Step 4 is wrong, you can replace it with this example: https://nix-community.github.io/home-manager/index.html#sec-flakes-standalone-stable

> Sure! Here's a step-by-step guide on how to enable flakes and add the `chaotic` repository to an Arch Linux system with Nix and Home Manager installed:
> 
> 1. Check if your friend has Nix version 2.4 or later installed. If not, upgrade to the latest version of Nix by running the following command:
> ```
> sudo nix-env -iA nixUnstable
> ```
> 
> 2. Update the Nix configuration to enable flakes. This can be done by creating the file `/etc/nix/nix.conf` (if it doesn't already exist) and adding the following line:
> ```
> experimental-features = nix-command flakes
> ```
> 
> 3. Create a new directory for the Nix configuration and initialize it as a Git repository:
> ```
> mkdir ~/.config/nix
> cd ~/.config/nix
> git init
> ```
> 
> 4. Create a new `flake.nix` file with the following contents:
> ```nix
> {
>   description = "My NixOS Home Manager configuration";
>   inputs = {
>     nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
>     chaotic.url = "github:chaotic-aur/chaotic-nix";
>   };
>   outputs = { self, nixpkgs, chaotic }: {
>     nixosConfigurations = {
>       home = nixpkgs.lib.nixosSystem {
>         system = "x86_64-linux";
>         modules = [
>           ./home.nix
>         ];
>         # Replace this with the device where the root partition resides
>         # e.g. "/dev/nvme0n1p1" or "/dev/sda1"
>         boot.loader.grub.device = "/dev/sda";
>       };
>     };
>     homeConfigurations = {
>       home = {
>         packages = with self.packages; [
>           # Add your packages here
>         ];
>         # Add your configuration here
>       };
>     };
>   };
> }
> ```
> This `flake.nix` file defines two outputs: `nixosConfigurations` for NixOS system configurations and `homeConfigurations` for Home Manager user configurations. It also adds the `chaotic` repository as an input and defines a basic NixOS configuration.
> 
> 5. Create a `home.nix` file with your Home Manager configuration. For example:
> ```nix
> { config, pkgs, ... }:
> 
> {
>   home.packages = with pkgs; [
>     neovim
>     git
>   ];
> 
>   home.file.".config/nvim/init.vim".source = ./init.vim;
> }
> ```
> This `home.nix` file installs the `neovim` and `git` packages and sets up a `init.vim` configuration file for Neovim.
> 
> 6. Run the following command to build the Home Manager configuration:
> ```
> nix build .#homeConfigurations.home.activationPackage
> ```
> 
> 7. Activate the Home Manager configuration by running:
> ```
> ./result/activate
> ```
> 
> 8. Verify that the Home Manager configuration is working as expected by checking the installed packages and configuration files.
> 
> That's it! Your friend should now have a working NixOS Home Manager configuration with the `chaotic` repository added as an input.


If it works for you, kindly let me know. If it worked after some extra effort, please describe it, so I can add it to a tutorial later.

**Comment by bayazidbh** [comment]
Alright, I tested it out, but I think there are some additions needed to be added to this repo's `flake.nix`.

Currently, this is my flake.nix:

<details><summary>My flake.nix</summary>
<p>

```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable"; # use nixpkgs-unstable as main nixpkgs source
    home-manager = {
      url = "github:nix-community/home-manager"; # home-manager unstable url
      inputs.nixpkgs.follows = "nixpkgs"; # inherit nixpkgs-unstable as main nixpkgs source
    };
    flatpaks.url = "github:GermanBread/declarative-flatpak/stable"; # declarative-flatpak, still WIP
    chaotic.url = "github:chaotic-cx/nyx/nyxpkgs-unstable"; # https://github.com/chaotic-cx/nyx#how-to-use-it
    # Add other inputs if needed
  };

  outputs = { self, nixpkgs, home-manager, flatpaks }:
  let
    # Generate a user-friendly version number.
    # version = builtins.substring 0 2 self.lastModifiedDate;

    # System types to support.  [ "x86_64-linux" "x86_64-darwin" "aarch64-linux" "aarch64-darwin" ];
    supportedSystems = [ "x86_64-linux" ];

    # Helper function to generate an attrset '{ x86_64-linux = f "x86_64-linux"; ... }'.
    forAllSystems = nixpkgs.lib.genAttrs supportedSystems;

    # Nixpkgs instantiated for supported system types.
    nixpkgsFor = forAllSystems (system: import nixpkgs { inherit system; });

  in
  {
    # Standalone home-manager configuration entrypoint
    homeConfigurations = {
    # declare a "username" or "username@hostname" specific configuration
      "fenglengshun@ostree-pc" = home-manager.lib.homeManagerConfiguration {
        pkgs = nixpkgs.legacyPackages.x86_64-linux; # Home-manager requires 'pkgs' instance
        modules = [
          ./pc/home.nix # device specific home.nix
          flatpaks.homeManagerModules.default # import declarative-flatpak module
          chaotic.nixosModules.default # default nix
        ];
      };
      "fenglengshun@neon-laptop" = home-manager.lib.homeManagerConfiguration {
        pkgs = nixpkgs.legacyPackages.x86_64-linux; # Home-manager requires 'pkgs' instance
        modules = [
          ./laptop/home.nix # device specific home.nix
          flatpaks.homeManagerModules.default # import declarative-flatpak module
        ];
      };
    };
  };
}

``` 

</p>
</details> 

Remove the two lines about chaotic, and it works. So the minimum to get chaotic-nyx working on non-NixOS home-manager **should** be:

<details><summary>minimum flake.nix for future instruction</summary>
<p>

```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable"; # use nixpkgs-unstable as main nixpkgs source
    home-manager = {
      url = "github:nix-community/home-manager"; # home-manager unstable url
      inputs.nixpkgs.follows = "nixpkgs"; # inherit nixpkgs-unstable as main nixpkgs source
    };
    chaotic.url = "github:chaotic-cx/nyx/nyxpkgs-unstable"; # add chaotic's github url
    # Add your other inputs
  };

  outputs = { self, nixpkgs, home-manager, flatpaks }:
  {
    # Standalone home-manager configuration entrypoint
    homeConfigurations = {
    # declare a "username" or "username@hostname" specific configuration
      ">INSERT YOUR USERNAME + OPTIONALLY HOSTNAME<" = home-manager.lib.homeManagerConfiguration {
        pkgs = nixpkgs.legacyPackages.x86_64-linux; # Home-manager requires 'pkgs' instance
        modules = [
          ./<folder>/home.nix # location to home.nix relative to flake.nix path, use ./home.nix if in the same folder
          chaotic.homeManagerModules.default # default chaotic-nyx module
        ];
      };
    };
  };
}

``` 

</p>
</details> 

However, switching to the flakes using chaotic's default module gets me the error:

<details><summary>nixosModules</summary>
<p>

```nix
home-manager switch
error: undefined variable 'chaotic'

       at /nix/store/mwh336zsyvhg95xicdqdf6yxbmc2ca6q-source/flake.nix:37:11:

           36|           flatpaks.homeManagerModules.default # import declarative-flatpak module
           37|           chaotic.nixosModules.default # default chaotic-nyx module
             |           ^
           38|         ];
error: undefined variable 'chaotic'

       at /nix/store/mwh336zsyvhg95xicdqdf6yxbmc2ca6q-source/flake.nix:37:11:

           36|           flatpaks.homeManagerModules.default # import declarative-flatpak module
           37|           chaotic.nixosModules.default # default chaotic-nyx module
             |           ^
           38|         ];
error: undefined variable 'chaotic'

       at /nix/store/mwh336zsyvhg95xicdqdf6yxbmc2ca6q-source/flake.nix:37:11:

           36|           flatpaks.homeManagerModules.default # import declarative-flatpak module
           37|           chaotic.nixosModules.default # default chaotic-nyx module
             |           ^
           38|         ];
```

</p>
</details> 

Looking at [declarative-flatpak's flake.nix](https://github.com/GermanBread/declarative-flatpak/blob/dev/flake.nix), it seems you guys would need separate module for handling home-manager? Based on what I've learned, you'd probably need to make a separate section for home-manager in flake.nix, or import it from a separate file.

One of the headache as I was trying to get a flake working, aside for scattered documentation and guides (don't use ChatGPT, it hallucinates WAY too much for Nix), is that I don't have `nixosSystem` and any variables involving nixos. Instead of `nixosConfigurations` I have to use `homeConfigurations` or `home-manager.lib.homeManagerConfiguration`. That's probably the blocker.

Also would probably need to make a list for actual home-manager pkgs and Options -- they're packages and configs that would be installed, set, and operates properly purely through `/home/$USER`. For pkgs and Options that needs root access, if you want to support them for non-NixOS then you can have a separate instruction, list, and module for [system-manager](https://github.com/numtide/system-manager).

So for now, I would suggest just adding "non-NixOS home-manager users are not currently supported".

**Comment by PedroHLC** [comment]
> Looking at [declarative-flatpak's flake.nix](https://github.com/GermanBread/declarative-flatpak/blob/dev/flake.nix), it seems you guys would need separate module for handling home-manager? Based on what I've learned, you'd probably need to make a separate section for home-manager in flake.nix, or import it from a separate file.****

You should be able to use it without a module and referring to the flake's packages directly. But yeah, we could make one HM module to make things easier too.

**Comment by PedroHLC** [comment]
To be more specific on the "you should be able to use it without a module":

- You can use https://nix-community.github.io/home-manager/nixos-options.html#nixos-opt-home-manager.extraSpecialArgs for forwarding `chaotic` from your `flake.nix`'s `outputs` to your `home.nix`.

- Once inside you can:
```nix
{ chaotic, ... }:
{
  programs.yt-dlp.package = chaotic.packages.x86-64-linux.yt-dlp_git;
}
```

**Comment by bayazidbh** [comment]
Okay, that works. I found what I needed to do:

1.) NOT forgetting to add `chaotic` into the opening statement of outputs on nix
2.) Add `extraSpecialArgs = { inherit chaotic; };` to `home-manager.lib.homeManagerConfiguration` as you say
3.) Add the full `chaotic.packages.x86_64-linux.<pkgs-name>` when adding to `home.packages`, following what you said. `chaotic.packages.${pkgs.hostPlatform.system}.<pkgs-name>` also works when adding to `home.packages` in the main home.nix file.

So, I would say the instruction could be something like:

<details><summary>instruction draft</summary>
<p>

Put in ~/.config/home-manager/flake.nix :

```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable"; # use nixpkgs-unstable as main nixpkgs source
    home-manager = {
      url = "github:nix-community/home-manager"; # home-manager unstable url
      inputs.nixpkgs.follows = "nixpkgs"; # inherit nixpkgs-unstable as main nixpkgs source
    };
    chaotic.url = "github:chaotic-cx/nyx/nyxpkgs-unstable"; # add chaotic's github url
    # Add your other inputs
  };

  outputs = { self, nixpkgs, home-manager, flatpaks, chaotic }:
  {
    # Standalone home-manager configuration entrypoint
    homeConfigurations = {
    # declare a "username" or "username@hostname" specific configuration
      ">INSERT YOUR USERNAME + OPTIONALLY HOSTNAME<" = home-manager.lib.homeManagerConfiguration {
        pkgs = nixpkgs.legacyPackages.x86_64-linux; # Home-manager requires 'pkgs' instance
        extraSpecialArgs = { inherit chaotic; }; # so that home-manager can correctly read chaotic.packages
        modules = [
          ./<folder>/home.nix # location to home.nix relative to flake.nix path, use ./home.nix if in the same folder
          ./<folder>/chaotic.nix # if you prefer a separate file for chaotic-nyx configs
          # chaotic.nixosModules.default # do not add the module, it does not currently work outside of NixOS - either don't write it, or comment it out
        ];
      };
    };
  };
}

``` 

Then, if you just use the one home.nix file:

```nix
{ config, pkgs, chaotic, ... }:

{

home.packages = with pkgs; [
    chaotic.packages.${pkgs.hostPlatform.system}.fastfetch # you may also use absolute system platform such as `x86_64-linux`
    # ... your other packages
    ];
}

```

Or, if you have a separate chaotic.nix file:

```nix
{ chaotic, ... }:
{
  home.packages = [
    chaotic.packages.x86_64-linux.fastfetch # `${pkgs.hostPlatform.system}` may not work, unless you have manually adjusted it for this file
  ];
}

```


</p>
</details> 

And yeah, the module doesn't work, adding `chaotic.nixosModules.default` results in:

<details><summary>Details</summary>
<p>

```nix

home-manager switch
error:
       … while evaluating a branch condition

         at /nix/store/8dq1grzr2g9ghh8nrwh15mn65pnp9qb1-source/lib/lists.nix:57:9:

           56|       fold' = n:
           57|         if n == len
             |         ^
           58|         then nul

       … while calling the 'length' builtin

         at /nix/store/8dq1grzr2g9ghh8nrwh15mn65pnp9qb1-source/lib/lists.nix:55:13:

           54|     let
           55|       len = length list;
             |             ^
           56|       fold' = n:

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attribute 'steam' missing

       at /nix/store/j5c9cby4i29zsjgfkzz6vdhaiw7cc6ag-source/modules/steam-compat-tools.nix:7:14:

            6| with lib; let
            7|   steamCfg = config.programs.steam;
             |              ^
            8|   cfg = config.chaotic.steam;

```

</p>
</details>

**Comment by PedroHLC** [comment]
Great, I'll make a module with it, but I'll add your instructions meanwhile.

Also, you can use `with` to shorten repeating our "full" path:
```nix
{ config, pkgs, chaotic, ... }:

{
  home.packages = with chaotic.packages.${pkgs.hostPlatform.system}; [
    fastfetch
    firedragon
  ];
}
```
