### ISSUE TITLE
[Request] Jovian-NixOS

### ISSUE THREAD

**Issue by IceDBorn** [chaotic-cx/nyx#572]
### Link to the package upstream website/repository

[Jovian-NixOS](https://github.com/Jovian-Experiments/Jovian-NixOS)

### Utility this package has for you

I use the packages and kernel provided by this flake for my steam deck!

### Do you consider the package(s) to be useful for every Chaotic-Nyx user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Are you sure the package isn't available upstream already?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by PedroHLC** [comment]
What is the idea here, cache all their packages?

**Comment by PedroHLC** [comment]
@IceDBorn I added some notes on how to make sure you'll be using the cached ones in the PR #574's description.
