### ISSUE TITLE
[Bug] No i915 gallium driver on mesa-git

### ISSUE THREAD

**Issue by duvas1** [chaotic-cx/nyx#593]
### What happens?

When using mesa-git package on NixOS, there's no i915 gallium driver, defaulting to LLVMPipe on X.org

### What is expected to happen?

Was expecting to have all drivers, since the source said "galliumDrivers = 'all' ", but it does not have the driver, I don't know why, but there is a workaround, which is compiling from source using a overlay.

### More information

I think it's pretty simple to "solve", since all we have to do is add "i915" on galliumDrivers, would be awesome to not have to compile on every single mesa_git update, since the driver is for mostly old pcs like mine, it will help others who want to try this package aswell.

**Comment by PedroHLC** [comment]
Are you sure you shouldn't be using crocus (which replaced i9**6**5)?

Anyway, feel free to add it to this line: https://github.com/chaotic-cx/nyx/blob/20813cd335222931394914d24cda8f7ea958fe28/pkgs/mesa-git/default.nix#L31

**Comment by duvas1** [comment]
No, unfortunately crocus wont work, maybe because my computer is too old. I'm gonna open a PR, thanks! 😁
