### ISSUE TITLE
[Request]  Enable intel xe kmd for mesa

### ISSUE THREAD

**Issue by MordragT** [chaotic-cx/nyx#623]
### Link to the package upstream website/repository

Hey it would be great if the intel xe kernel module support could be enabled for mesa.
I haven't investigated it any further but I believe adding "-Dintel-xe-kmd=enabled" to meson flags should do the trick.

### Do you consider the package(s) to be useful for every Chaotic-Nyx user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Are you sure the package isn't available upstream already?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Alanazane** [comment]
Merged :rocket:

**Comment by PedroHLC** [comment]
Present in yesterday's bump.

**Comment by MordragT** [comment]
Thank you!

**Comment by piyoki** [comment]
Hi all, I also look forward to the same request above. According to https://wiki.archlinux.org/title/Intel_graphics#Testing_the_new_experimental_Xe_driver, it is required to add the `"-Dintel-xe-kmd=enabled"` flag when compiling mesa from source. Could we revisit this topic, please?

**Comment by Alanazane** [comment]
As mentioned above the build flag shouldn't be necessary any more, I've successfully used the Xe kmd on an intel arc machine with nyx since the merge of that mr :)

**Comment by piyoki** [comment]
> As mentioned above the build flag shouldn't be necessary any more, I've successfully used the Xe kmd on an intel arc machine with nyx since the merge of that mr :)

Thanks for the notes. I will have a try today.
