### ISSUE TITLE
[Request] Instead of setting linux_cachyos, assert AMD_PRIVATE_COLOR for HDR 

### ISSUE THREAD

**Issue by PedroHLC** [chaotic-cx/nyx#630]
### What happens?

Presently, `chaotic.hdr` sets kernel to `linux_cachyos`. But HDR has been merged into Linux 6.8, so this is not needed anymore. Instead, we want any 6.8+ kernel built with `-DAMD_PRIVATE_COLOR` in `KCFLAGS`.

### What is expected to happen?

If the user has an LTS kernel, he should be warned that it does not support HDR, and advised to upgrade to either 6.8+ with `AMD_PRIVATE_COLOR` or `linux_cachyos` (needs rebuild with `AMD_PRIVATE_COLOR` rn).

**Comment by SuperSamus** [comment]
I may be wrong, but doesn't Linux 6.8 require `AMD_PRIVATE_COLOR` for HDR to function?
(`https://github.com/ValveSoftware/gamescope/pull/1149`)

**Comment by PedroHLC** [comment]
> I may be wrong, but doesn't Linux 6.8 require `AMD_PRIVATE_COLOR` for HDR to function? 

In this case, I wonder if I can assert that config instead. Providing both gamescope (with and without patch) should be easy.

**Comment by PedroHLC** [comment]
UPDATE: I've added the patches to gamescope_git, and `AMD_PRIVATE_COLOR` to the kernels: and it works, gamesocpe puts it in HDR and shows the color properly.

But, right now, `gamescope_git` is producing an 80% corrupt output on my end.

**Comment by SuperSamus** [comment]
> `gamescope_git` is producing an 80% corrupt output on my end

Known issue: `https://github.com/ValveSoftware/gamescope/issues/1191`
Staying on commit `14a1db3a` should fix it.
