### ISSUE TITLE
[Bug Report] scx_lavd failed to run

### ISSUE THREAD

**Issue by miooochi** [chaotic-cx/nyx#684]
### What happens?

`scx_lavd` failed to start.

### What is expected to happen?

`scx_lavd` runs flawlessly.

### If possible, please attach logs

```console
⯁ flake git:(master) ✗ ❯❯❯ sudo scx_lavd
Error: Failed to load BPF program

Caused by:
    Invalid argument (os error 22)
```

### More information

nix store path

`/nix/store/m890hnwrhdn1jn1vd01kd45ygrd48bbx-scx-unstable-20240326-5bfd90bd6/bin/scx_lavd`

flake.lock

```diff
       "locked": {
-        "lastModified": 1713212932,
-        "narHash": "sha256-FnKDhx5w9KRUJR0ZEI4kpL+KtAv2utAs6+ovDz1SmHo=",
+        "lastModified": 1713554347,
+        "narHash": "sha256-Li6DK5JqKesOhTBwSoqxWzOxUR0pcPxE/L7vVyEsZpM=",
         "owner": "chaotic-cx",
         "repo": "nyx",
-        "rev": "a2f034e707ad9e2be09454f171acd805015ae245",
+        "rev": "72c35184e8260a612b00977d0bb26d63cb385cb0",
         "type": "github"
       },
```

**Comment by LDprg** [comment]
Same for me. Is this related to https://github.com/sched-ext/scx/issues/203?
It seems like a wrong bpftools version (7.3.0 on my system instead of 7.4.0).

**Comment by miooochi** [comment]
> Same for me. Is this related to [sched-ext/scx#203](https://github.com/sched-ext/scx/issues/203)? It seems like a wrong bpftools version (7.3.0 on my system instead of 7.4.0).

I've escalated it in to the project maintainers - https://github.com/sched-ext/scx/issues/244. Let's see how it goes.

**Comment by PedroHLC** [comment]
Important to mention that I didn't try to reproduce it yet, as well didn't try to bump it.

**Comment by PedroHLC** [comment]
Ok, I can confirm it now:
![image](https://github.com/chaotic-cx/nyx/assets/1368952/bf6fdea3-776a-453e-b5df-f64369112995)

**Comment by miooochi** [comment]
According to https://github.com/sched-ext/scx/issues/244#issuecomment-2083972846, @PedroHLC would you like to try out the fix?

**Comment by PedroHLC** [comment]
Fixed by https://github.com/sched-ext/scx/pull/247 and deployed in 8cfa2aa1528faa6319e2e5ab664ff463ba57708c
