### ISSUE TITLE
[Bug] linuxPackages_cachyos-lto.nvidia_x11 fails to build (fix included)

### ISSUE THREAD

**Issue by silvanshade** [chaotic-cx/nyx#687]
### What happens?

The `linuxPackages_cachyos-lto.nvidia_x11` fails to build due to permission errors related to  ThinLTO.

One would encounter this with the following configuration:

```nix
{
  boot.kernelPackages = pkgs.linuxPackages_cachyos-lto;
  hardware.nvidia.package = config.boot.kernelPackages.nvidia_x11;
}
```

### What is expected to happen?

Ideally `linuxPackages_cachyos-lto.nvidia_x11` should build without errors.

### More information

It's possible to fix the ThinLTO permission errors by using the `--thinlto-cache-dir=<dir>` option and specifying a directory with appropriate permissions.

For example, you can create a suitable directory with the following:

```
sudo mkdir -p -m0770 /var/cache/clang-thinlto
sudo chown root:nixbld /var/cache/clang-thinlto
```

Next you need to add the path to the build sandbox paths and override the `makeFlags` of the kernel:

```nix
{
  nix.settings.extra-sandbox-paths = [
    "/var/cache/clang-thinlto"
  ];
  nixpkgs.overlays = [
    (final: prev: {
      linuxPackages_cachyos-lto-with-fixed-nvidia = final.linuxPackages_cachyos-lto.override (linuxPackagesArgs: {
        linuxPackagesFor = kernel: linuxPackagesArgs.linuxPackagesFor (
          kernel.overrideAttrs (kernelAttrs: {
            makeFlags = kernelAttrs.makeFlags ++ [
              "KBUILD_LDFLAGS+=--thinlto-cache-dir=/var/cache/clang-thinlto"
            ];
          })
        );
      });
    })
  ];
  boot.kernelPackages = pkgs.linuxPackages_cachyos-lto-with-fixed-nvidia;
  hardware.nvidia.package = config.boot.kernelPackages.nvidia_x11;
}
```

**Comment by silvanshade** [comment]
Maybe it would be reasonable to add special handling for the nvidia driver in the LTO case to automatically set this ThinLTO cache dir in order to avoid build failures?

**Comment by PedroHLC** [comment]
For starters, add it to this list:
https://github.com/chaotic-cx/nyx/blob/8cb2e4eb3422d099ce80c95accfbba917c45622d/pkgs/linux-cachyos/default.nix#L42

This triggers the fixes from:
https://github.com/chaotic-cx/nyx/blob/8cb2e4eb3422d099ce80c95accfbba917c45622d/pkgs/linux-cachyos/lib/llvm-module-overlay.nix#L8

**Comment by silvanshade** [comment]
> For starters, add it to this list:
> 
> https://github.com/chaotic-cx/nyx/blob/8cb2e4eb3422d099ce80c95accfbba917c45622d/pkgs/linux-cachyos/default.nix#L42
> 
> This triggers the fixes from:
> 
> https://github.com/chaotic-cx/nyx/blob/8cb2e4eb3422d099ce80c95accfbba917c45622d/pkgs/linux-cachyos/lib/llvm-module-overlay.nix#L8

Oh interesting, I'll try that. Thanks.

> Edit: Also, I've seen users in the past just replacing it with ordinary `linuxPackagesFor_cachyos.nvidia-x11` and it worked (you have to use `.extend` in the Packages attrset, no need for an overlay, you can do it directly in the kernel option)

Yeah this does work and I was using it for awhile. Unfortunately in my case this results in two builds of the kernel since I use the `znver4` package from the AMD64 microarchitectures package set (and I sometimes add additional `KCFLAGS`). So a solution that didn't require that would be nice.

**Comment by diniamo** [comment]
This happens for xpadneo as well:
```nix
    hardware.xpadneo.enable = true;
```

**Comment by diniamo** [comment]
@PedroHLC any update on this?

**Comment by PedroHLC** [comment]
Closing this, same as https://github.com/chaotic-cx/nyx/issues/864#issuecomment-2331700374

**Comment by ptr1337** [comment]
thinlto cache got deprecated tho.

**Comment by silvanshade** [comment]
> thinlto cache got deprecated tho.

@ptr1337 are you sure it's deprecated? I don't see anything about deprecation in `ld.lld --help` nor anywhere in the llvm-project sources or repo.

**Comment by silvanshade** [comment]
I just tried the approach I described above and it still works with linux 6.11.4 and clang 19 (and presumably 20 since the lto cache options are still there).

I wanted to add a note though in case anyone ran across this issue in the future:

If you try to compile with the nvidia driver with `hardware.nvidia.open = true` you will get an error about the `<kernel>-modules-shrunk` derivation not being allowed to refer to the `<kernel>` derivation path.

This is seemingly due to the modules closure having `allowedReferences` set to disallow references other than itself. I'm not sure how to work around this but at least for now you can just disable the open modules (`hardware.nvidia.open = false`) and everything will compile and work.

**Comment by ptr1337** [comment]
> > thinlto cache got deprecated tho.
> 
> @ptr1337 are you sure it's deprecated? I don't see anything about deprecation in `ld.lld --help` nor anywhere in the llvm-project sources or repo.

It does not get used by the linux kernel anymore, and got removed there.

**Comment by silvanshade** [comment]
@ptr1337 I understand what you mean now. But it seems fine to use it in manually specified `KBUILD_LDFLAGS`, right? Or are you suggesting there is some deeper problem with using it? I don't know the reasoning behind why the Kconfig option for it was removed (in fact I forgot there was one).

**Comment by ptr1337** [comment]
> @ptr1337 I understand what you mean now. But it seems fine to use it in manually specified `KBUILD_LDFLAGS`, right? Or are you suggesting there is some deeper problem with using it? I don't know the reasoning behind why the Kconfig option for it was removed (in fact I forgot there was one).

Well, if that works for NixOS, then its fine.
