### ISSUE TITLE
[Bug] linux-cachyos iwlwifi crashes

### ISSUE THREAD

**Issue by LDprg** [chaotic-cx/nyx#694]
### What happens?

Sometimes iwlwifi crashes and I have no wireless network anymore. Seems to happen more often when using nixos rebuild or playing around with sched_ext.

reloading the module with `sudo rmmod iwlmvm iwlwifi` and `sudo modprobe iwlmvm iwlwifi` fixes the problem until the next crash

### What is expected to happen?

Wifi working fine without any crashes.

### If possible, please attach logs

Kernel logs are attached (crash is on the end of log).
[system.log](https://github.com/chaotic-cx/nyx/files/15142388/system.log)

### More information

neofetch:
```shell
          ▗▄▄▄       ▗▄▄▄▄    ▄▄▄▖            ld@LD-Laptop 
          ▜███▙       ▜███▙  ▟███▛            ------------ 
           ▜███▙       ▜███▙▟███▛             OS: NixOS 24.05.20240425.7bb2ccd (Uakari) x86_64 
            ▜███▙       ▜██████▛              Host: ASUSTeK COMPUTER INC. FA506QM 
     ▟█████████████████▙ ▜████▛     ▟▙        Kernel: 6.8.7-cachyos 
    ▟███████████████████▙ ▜███▙    ▟██▙       Uptime: 1 hour, 23 mins 
           ▄▄▄▄▖           ▜███▙  ▟███▛       Packages: 2892 (nix-system), 1274 (nix-user) 
          ▟███▛             ▜██▛ ▟███▛        Shell: fish 3.7.1 
         ▟███▛               ▜▛ ▟███▛         Resolution: 1920x1080 
▟███████████▛                  ▟██████████▙   DE: Plasma 6.0.4 (Wayland) 
▜██████████▛                  ▟███████████▛   WM: kwin 
      ▟███▛ ▟▙               ▟███▛            Icons: Sweet-Red [GTK2/3] 
     ▟███▛ ▟██▙             ▟███▛             Terminal: kitty 
    ▟███▛  ▜███▙           ▝▀▀▀▀              Terminal Font: monospace 11.0 
    ▜██▛    ▜███▙ ▜██████████████████▛        CPU: AMD Ryzen 7 5800H with Radeon Graphics (16) @ 4.463GHz 
     ▜▛     ▟████▙ ▜████████████████▛         GPU: NVIDIA GeForce RTX 3060 Mobile / Max-Q 
           ▟██████▙       ▜███▙               GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
          ▟███▛▜███▙       ▜███▙              Memory: 8986MiB / 31492MiB 
         ▟███▛  ▜███▙       ▜███▙
         ▝▀▀▀    ▀▀▀▀▘       ▀▀▀▘                                     
                                                                      
```
Output of `nix-shell -p nix-info --run "nix-info -m"`:

```shell
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.7-cachyos, NixOS, 24.05 (Uakari), 24.05.20240425.7bb2ccd`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/370qy3d3wg9zhbn5a3dcv6k1q1iigfh4-source`
```

**Comment by PedroHLC** [comment]
Cc @ptr1337

**Comment by ptr1337** [comment]
> Sometimes iwlwifi crashes and I have no wireless network anymore. Seems to happen more often when using nixos rebuild or playing around with sched_ext.

So, it seems when there is a higher load it does crash?
We are actually not changing anything on the driver part, besides on ATH11k for the steam deck.

**Comment by LDprg** [comment]
I wasn't able to reproduce on latest kernel, I will test with zen.

I tried running sysbench cpu for high cpu load, to test if it would cause the same problem, but I wasn't able to cause iwifi crashing.

**Comment by LDprg** [comment]
@ptr1337 I was trying with zen/xanmod kernels and not iwlwifi issues yet. I am only getting lag spikes from time to time with zen, but nothing related to iwlwifi.

It seems that short high load spikes are the issue, since running benchmarks pushing cpu and gpu to 100% cause no wifi loss. Starting firefox or high load compilations sometimes crashes iwlwifi. It doesn't seem to appear at random with no app starting. Higher load in general however causes the issue with iwlwifi to appear more frequent.

Note this is pure assumption since I didn't found a way to reproduce a 100%.

**Comment by LDprg** [comment]
@ptr1337 I have updated my flake recently and uninstalled sched_ext. Now I don't get any crashes.

I am not sure what exactly caused it (random bug in kernel or schedext). But from my side it seems fixed and can be closed. 

Should this issues be kept open, in order to track if the issue is related to sched_ext?

**Comment by ptr1337** [comment]
> @ptr1337 I have updated my flake recently and uninstalled sched_ext. Now I don't get any crashes.
> 
> I am not sure what exactly caused it (older kernel or schedext). But from my side it seems fixed and can be closed.
> 
> Should this issues be kept open, in order to track if the issue is related to sched_ext? (I mean it is probaply just a random kernel bug)

If you don't use any scx-sched scheduler, then this is completly unrelated.
