### ISSUE TITLE
[Request] Make linux-cachyos also part of pkgsx86_64_v3-core

### ISSUE THREAD

**Issue by LDprg** [chaotic-cx/nyx#696]
### Link to the package upstream website/repository

No external link.

### Do you consider the package(s) to be useful for every Chaotic-Nyx user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Are you sure the package isn't available upstream already?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

As title says precompile and cache a linux-cachyos version for pkgsx86_64_v3-core. Since this would benefit like 99% of all nyx users (that use pkgsx86_64_v3-core cached packages).

**Comment by PedroHLC** [comment]
Closing this, don't have time to do it myself, if someone is that much interested, please open a PR instead.
