### ISSUE TITLE
[Request] Add ACS override to linux-cachyos

### ISSUE THREAD

**Issue by ilya-fedin** [chaotic-cx/nyx#780]
### Link to the package upstream website/repository

https://github.com/benbaker76/linux-acs-override

### Utility this package has for you

I want to use the cachyos kernel but the lack of ACS override is a deal breaker for me :(

### Do you consider the package(s) to be useful for every Chaotic-Nyx user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Are you sure the package isn't available upstream already?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by ptr1337** [comment]
This patch is already included in linux-cachyos

**Comment by ilya-fedin** [comment]
Hm, indeed, the previous time I grepped dmesg, I believe it had no lines about acs override... Sorry for the noise.
