### ISSUE TITLE
[Support Request] linux-cachyos 6.9.8 is not in the binary cache server

### ISSUE THREAD

**Issue by piyoki** [chaotic-cx/nyx#797]
### What happens?

It came to me that `linux-cachyos` 6.9.8 cannot be fetched from the binary cache server. Instead, it always builds from source. Ref: https://github.com/chaotic-cx/nyx/commit/282550a7354dd3830fa9453049a24a7938070021

### What is expected to happen?

Expect to fetch binary from the cache server.

### If possible, please attach logs

![image](https://github.com/user-attachments/assets/5a77c2a0-029c-46b8-9ab0-680178d8f2bf)

**Comment by PedroHLC** [comment]
CI says otherwise: https://github.com/chaotic-cx/nyx/actions/runs/9905388851/job/27364837423#step:7:212

Can you try all the steps at https://www.nyx.chaotic.cx/#why-am-i-building-a-kernel-basic-cache-troubleshooting and let me know which is failing?

**Comment by piyoki** [comment]
Hey @PedroHLC, I can confirm that the commit https://github.com/chaotic-cx/nyx/commit/3dee707e8b330529e0d4f6dc41505ace310728e5 has resolved the issue.
