### ISSUE TITLE
[Bug] Cannot use with channels

### ISSUE THREAD

**Issue by MrQubo** [chaotic-cx/nyx#806]
### What happens?

chaotic-nyx cannot be used with channels. Trying to `import <chaotic-nyx> {}` givers error:
```
error: opening file '/nix/store/1yvbfdssg30yi7lqyz096116ssa6kpkf-chaotic-nyx/chaotic-nyx/default.nix': No such file or directory
```

### What is expected to happen?

It should be possible to import chaotic-nyx with channels.

### More information

Channel can be added with `nix-channel --add https://github.com/chaotic-cx/nyx/archive/master.tar.gz chaotic-nyx`.

**Comment by PedroHLC** [comment]
I am not interested in providing and later maintaining support for channels, as they add even more impurity that I will later have to troubleshoot when users show up with unreproducible issues.

If you really want to try, then import `<chaotic-nyx>/overlays` instead, you'll need to provide something like flakes' inputs to it. E.g.,

```nix
import <chaotic-nyx>/overlays { flakes = {
  nixpkgs = { ... };
  self = { ... };
  jovian = { ... };
}; }
```

Also, using `archive/master.tar.gz` is wrong, we don't have a cache for our `main` branch, only `nyxpkgs-unstable` is guaranteed to have everything cached, and only for the nixpkgs' commit we're pinning in our `flake.lock`.

---

I will not support channels, but I accept PRs for other flakes-like pinning+purity solutions.
