### ISSUE TITLE
"scx_bpfland" is not a valid value for the chaotic.scx.scheduler option.

### ISSUE THREAD

**Issue by HippieMitch** [chaotic-cx/nyx#812]
### What happens?

Added chaotic.scx.scheduler = "scx_bpfland";
to my configuration and ran a nixos-rebuild switch.   After this I got an error message that states that it is not a valid value.

### What is expected to happen?

The system should not throw an error and successfully switch to using scx-bpfland.

### If possible, please attach logs

 error: A definition for option `chaotic.scx.scheduler' is not of type `one of "scx_central", "scx_flatcg", "scx_lavd", "scx_layered", "scx_nest", "scx_pair", "scx_qmap", "scx_rlfifo", "scx_rustland", "scx_rusty", "scx_simple", "scx_userland"'. Definition values:
       - In `/nix/store/6dlikr3bkn2bhzs0xic14a2j4gpnxkzi-source/system/kernels/cachy-lto-scx.nix': "scx_bpfland"

### More information

I see scx-bpfland in the repo so it appears that it should be part of that type list.

**Comment by PedroHLC** [comment]
Please open a PR 🥹

**Comment by HippieMitch** [comment]
Done.  I'll close this ha.
