### ISSUE TITLE
[Support Request] Binary cache for linux-cachyos

### ISSUE THREAD

**Issue by piyoki** [chaotic-cx/nyx#841]
### What happens?

When attempting to download the `linux-cachyos` binary cache from the dedicated cache server, the download either fails or is significantly slower than expected. This issue prevents the successful installation of the linux-cachyos package, causing build processes to either hang indefinitely or fail entirely.

Specifically, this commit - https://github.com/chaotic-cx/nyx/commit/43811177550cb9bf08277af59fe222a15ef13a85

### What is expected to happen?

The linux-cachyos binary cache should be downloaded quickly and reliably from the dedicated cache server, allowing the package to be installed without any delays or failures. The cache server should be responsive and provide the binaries as needed for the build process to proceed smoothly.

### More information

I sincerely request your support in resolving this issue as it has become a significant blocker for my work. I've taken the following steps to troubleshoot:

* Cleared Local Cache: I tried clearing the local cache to see if that would resolve the issue, but unfortunately, it did not help.
* Reconfigured Cache Server Settings: I adjusted the cache server settings to ensure they were correct, but this didn't solve the problem either.
* Tested Connection: I tested my connection to the server and confirmed that there are no local network issues that might be causing the problem.

Despite these efforts, the issue persists, and I'm unable to proceed with my tasks. The download failure is affecting my ability to work with the `linux-cachyos` package, which is critical for my current project.

I'm reaching out with the hope that your team can help diagnose the issue and provide a solution. If you need any additional information from my end, I'm more than willing to assist. I greatly appreciate your time and support in addressing this matter.

Thank you in advance for your help.

**Comment by PedroHLC** [comment]
If you read https://nyx.chaotic.cx/ or README you'll find out that our "main" branch is for development, and it's not cached. The "nyxpkgs-unstable" is cached and the suggested one for use. By using that, you'll find a linux-cachyos package that you can use out of the box right now.

Our builder should finish building the new version soon and the new branch shall update automatically to it. 

Sorry for being late on this one, I've had too much work during the week.

**Comment by piyoki** [comment]
> If you read https://nyx.chaotic.cx/ or README you'll find out that our "main" branch is for development, and it's not cached. The "nyxpkgs-unstable" is cached and the suggested one for use. By using that, you'll find a linux-cachyos package that you can use out of the box right now.
> 
> Our builder should finish building the new version soon and the new branch shall update automatically to it.
> 
> Sorry for being late on this one, I've had too much work during the week.

Hey @PedroHLC, thanks for your kind notes! No worry and sorry for the prompt request. I will have a try followed by your advice. Cheers!

**Comment by piyoki** [comment]
As an update, I can confirm that by specifying the [HEAD](https://github.com/chaotic-cx/nyx/commit/b8b1c616f8b869af7bce3179ad423e3d45b0d079) commit in the `nyxpkgs-unstable` branch, I managed it get the binary cache from the cache server! 

Ref: https://github.com/piyoki/nixos-config/blob/master/flake.nix#L130

**Comment by PedroHLC** [comment]
@piyoki latest commits on main (aka master) is deployed to `nyxpkgs-unstable` (100% updated and cached).

**Comment by piyoki** [comment]
> @piyoki latest commits on main (aka master) is deployed to `nyxpkgs-unstable` (100% updated and cached).

Thanks for the update!

**Comment by piyoki** [comment]
I'd like to also share the way how I keep track on the `nyxpkgs-unstable` branch. Ref: https://github.com/piyoki/nixos-config/issues/289

I have a dedicated GitHub Action [workflow](https://github.com/piyoki/nixos-config/blob/master/.github/workflows/cron-poll-repo-changes.yml), which monitors any changes made to https://github.com/chaotic-cx/nyx/blob/main/pkgs/linux-cachyos/versions.json on a daily basis.

As a result, I will be notified if the new kernel is available in the cache server.
