### ISSUE TITLE
[Bug] linuxPackages_cachyos causes problems with Distrobox containers

### ISSUE THREAD

**Issue by KingKrouch** [chaotic-cx/nyx#856]
### What happens?

When I use the CachyOS kernel, and try to run Distrobox (or anything with containers really), I get an error similar to this:

```
❯ distrobox enter Coding_Toolchain
Error: unable to start container "e0857ff9ce692398b488da395d143d604cf87eb5794343db3189892412e43a3a": crun: mkdir `/sys/fs/selinux`: Permission denied: OCI permission denied
```

### What is expected to happen?

I would reasonably expect that it would work without configuring anything extra.

### More information

I was digging around to see if there was anything kernel specific that was causing this issue, and I noticed that when I revert to the NixOS kernel, it doesn't have this issue.

Based on what I've heard others discuss when I asked for some assistance with figuring this issue out, this is possibly an SELinux related error. However, when I try and run sestatus in the terminal, it says that SELinux is disabled.

So I ended up looking at the repository to see what the kernel compilation flags were set to, and I noticed that SELinux support was enabled in the kernel, so here's what I ended up trying to see if I could disable it:

```
boot.kernelPackages = pkgs.linuxPackages_cachyos;
boot.kernelPatches = [ { # We need to disable SELinux in the case of CachyOS, as it causes issues with Distrobox.
  name = "disable_selinux";
  patch = null;
  extraConfig = ''
    CONFIG_SECURITY_SELINUX unset
    CONFIG_SECURITY_SELINUX_BOOTPARAM unset
    CONFIG_SECURITY_SELINUX_DEVELOP unset
    CONFIG_SECURITY_SELINUX_AVC_STATS unset
    CONFIG_SECURITY_SELINUX_SIDTAB_HASH_BITS unset
    CONFIG_SECURITY_SELINUX_SID2STR_CACHE_SIZE unset
  '';
} ];
boot.kernelParams = [ "selinux=0" ];
chaotic.scx.enable = true; # by default uses scx_rustland scheduler
 ```
This still didn't really resolve the issue.

**Comment by PedroHLC** [comment]
I must declare first that [I'm not a big fan of `distrobox`.](https://I%20like%20to%20reinvent%20the%20wheel%20with%20shell%20and%20try%20to%20support%20all%20edge-cases%20out-of-box%2C%20which%20is%20precisely%20what%20distrobox%20does.%20But%20even%20for%20me%2C%20its%20source%20%28especially%20their%20distrobox-enter%20scripts%2C%20their%20version%20of%20cloud-init%29%20gives%20me%20nightmares.%20It%20only%20looses%20to%20airgeddon)

But I think your guess of the culprit is wrong:
```
╰─λ uname -a
Linux desktop 6.10.6-cachyos #1-NixOS SMP PREEMPT_DYNAMIC Mon Aug 19 04:05:40 UTC 2024 x86_64 GNU/Linux
╭─pedrohlc at desktop in /etc/nixos
╰─λ distrobox enter archlinux
何でもは知らないわよ。知ってることだけ
╭─pedrohlc at desktop in /run/host/etc/nixos
╰─λ pacman -Sy
error: you cannot perform this operation unless you are root.
╭─pedrohlc at desktop in /run/host/etc/nixos
╰─λ sudo pacman -Sy
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 ```

**Comment by KingKrouch** [comment]
> But I think your guess of the culprit is wrong

That is a fair assessment to make, I'm willing to admit that I'm likely incorrect in that theory as you said, but I'm wondering, if there's any default variables that are set when you include the "inputs.chaotic.nixosModules.default" module in the flakes.nix file. When I remove that and the kernel stuff that I added to my config, distrobox works fine, but I'd suspect since from my tests SELinux returned false, that there's something likely going on.

**Comment by PedroHLC** [comment]
Related to virtualization, I have these set:

```
  boot.enableContainers = false;
  virtualisation.podman = {
    enable = true;
    dockerCompat = true;
  };
```

Nothing cgroup related to impact crun (it is running v2 which should be what everyone gets now with latest nixos-unstable). No group that should impact containerization.

As far I'm aware, we don't have modules changing any cgroup/crun/runc option.

**Comment by PedroHLC** [comment]
@KingKrouch any update?

**Comment by KingKrouch** [comment]
So I recently did a system update (With the NixOS kernel this time), and for some reason, now it's causing this same exact issue there too (Not with the Arch distrobox surprisingly), so I am going to conclude by saying that it's likely a Distrobox issue at this point.

Apologies for the issue ticket.

**Comment by Technetium1** [comment]
@KingKrouch should definitely report to Distrobox, with this linked for context.

**Comment by KingKrouch** [comment]
> @KingKrouch should definitely report to Distrobox, with this linked for context.

I'll report it to them soon if I can't resolve it.

But I figured I'd attempt to fork the repo, change some of the bits used to compile the kernel, and then try this again.
