### ISSUE TITLE
[Bug] Build failure with `linuxPackages_cachyos{-lto}` and `zfs_cachyos`

### ISSUE THREAD

**Issue by magneticflux-** [chaotic-cx/nyx#864]
### What happens?

I'm trying to synchronize the versions of ZFS user tools and the kernel by setting these variables in my config:
```nix
{ inputs, config, lib, pkgs, ... }:
{
  boot = {
    zfs = {
      package = pkgs.linuxPackages_cachyos.zfs_cachyos;
    };
    kernelPackages = pkgs.linuxPackages_cachyos;
  };
}
```

I also tried with `cachyos-lto` like this:
```nix
{ inputs, config, lib, pkgs, ... }:
{
  boot = {
    zfs = {
      package = pkgs.linuxPackages_cachyos-lto.zfs_cachyos;
    };
    kernelPackages = pkgs.linuxPackages_cachyos-lto;
  };
}
```

And with the "main" package:
```nix
{ inputs, config, lib, pkgs, ... }:
{
  boot = {
    zfs = {
      package = pkgs.zfs_cachyos;
    };
    kernelPackages = pkgs.linuxPackages_cachyos-lto;
  };
}
```

When using `linuxPackages_cachyos`, the build fails in building the `initrd` like this:
```
last 25 log lines:
> /etc/modprobe.d/debian.conf -> /nix/store/vqrqngrh56y42jj1jb3h18p87kzls6mg-kmod-debian-aliases.conf-30+20230601-2
> /etc/modprobe.d/nixos.conf -> /nix/store/0ldj0qad7xqhxyb0pbns246paaqsfsll-etc-modprobe.d-nixos.conf
> /etc/modprobe.d/systemd.conf -> /nix/store/b11is5q9wgl4jjqs43x9qi22kljvpydj-systemd-256.4/lib/modprobe.d/systemd.conf
> /etc/modprobe.d/ubuntu.conf -> /nix/store/0d6a80aqk25x6a8xrplmzf9kv1gvjw64-initrd-kmod-blacklist-ubuntu
> /etc/modules-load.d/nixos.conf -> /nix/store/nnxdljys44s4p5w620a386364cd2g4q5-initrd-nixos.conf
> /etc/os-release -> /nix/store/r8s4my24id5ss2abg6cxhbm47p6isrvk-initrd-release
> /etc/passwd -> /nix/store/na3dp84hd852f55r04v6l9kqqr509w59-initrd-passwd
> /etc/shadow -> /nix/store/95ff8yi4z4bqlac2n3sq06dvrjdpwzgw-initrd-shadow
> /etc/shells -> /nix/store/dyx31l1f53qib48415cvv7rrdg3gjw3s-initrd-shells
> /etc/sysctl.d/nixos.conf -> /nix/store/h2icbmvhjkkl2401pi7s881675vdzb4x-initrd-nixos.conf
> /etc/systemd/system -> /nix/store/pbhm3k5kc5mgsm37k5yhwr9hddj2pgrl-initrd-units
> /etc/systemd/system.conf -> /nix/store/r9fh2ifsdvg8wyimxsp0f0dm78r0rryn-initrd-system.conf
> /etc/udev/rules.d -> /nix/store/3c5hhls1viqny8qznc98i61dlxpdga2w-initrd-udev-rules
> /etc/vconsole.conf -> /nix/store/aa54jy04hbnng6cnjrkjpbdh8149f8c4-vconsole.conf
> /init -> /nix/store/b11is5q9wgl4jjqs43x9qi22kljvpydj-systemd-256.4/lib/systemd/systemd
> /lib -> /nix/store/xmcgm74a0az0kxccpc2bybbzxmh9bzyw-linux-6.10.7-modules-shrunk/lib
> /sbin -> /nix/store/nm55fiihyxhhswz9hky46sgcw4chnm76-initrd-bin-env/sbin
> /tmp/.keep -> /nix/store/mqb0lwhmbvgb0z2qw9kacmn86cbnn4pd-initrd-.keep
> Error: failed to get symlink metadata for "/nix/store/bpda1h4n43yylzn77jldqs238l1a17xq-zfs-kernel-2.2.5-6.10.7/lib/udev"
>
> Caused by:
>     No such file or directory (os error 2)
>
> Location:
>     src/main.rs:262:22
For full logs, run 'nix log /nix/store/6mcxb1pf86xnvrj88w1dsxckrg4840w8-initrd-linux-6.10.7.drv'.
```

When using `linuxPackages_cachyos-lto`, with or without using the "main" package, the build fails in `zfs-kernel` like this:
```
last 25 log lines:
> checking whether objtool header is available... linux/objtool.h
> checking whether wait_queue_entry_t exists... yes
> checking whether /dev/zfs minor is available... 249
> checking whether DECLARE_EVENT_CLASS() is available... no
> checking for available kernel interfaces... done
> checking whether access_ok() has 'type' parameter... no
> checking whether global_node_page_state() exists... yes
> checking whether global_zone_page_state() exists... yes
> checking whether enum node_stat_item contains NR_FILE_PAGES... no
> checking whether enum node_stat_item contains NR_INACTIVE_ANON... no
> checking whether enum node_stat_item contains NR_INACTIVE_FILE... no
> checking whether enum zone_stat_item contains NR_FILE_PAGES... no
> checking whether enum zone_stat_item contains NR_INACTIVE_ANON... no
> checking whether enum zone_stat_item contains NR_INACTIVE_FILE... no
> checking whether global_page_state enums are sane... no
> NR_FILE_PAGES in either node_stat_item or zone_stat_item: NOT FOUND
> configure: error:
>         *** None of the expected "global page state" interfaces were detected.
>         *** This may be because your kernel version is newer than what is
>         *** supported, or you are using a patched custom kernel with
>         *** incompatible modifications.
>         ***
>         *** ZFS Version: zfs-2.2.4-1
>         *** Compatible Kernels: 3.10 - 6.8
>
For full logs, run 'nix log /nix/store/v1qgr1amiypyrgc161bl7a29fj6hhxvm-zfs-kernel-2.2.5-6.10.7.drv'.
```

### What is expected to happen?

I should be able to use the ZFS package inside `linuxPackages` to track the current version of userspace tools.

### More information

I found one scenario that works, but it might just be a coincidence because the packages happen to align right now:

```nix
{ inputs, config, lib, pkgs, ... }:
{
  boot = {
    zfs = {
      package = pkgs.zfs_cachyos;
    };
    kernelPackages = pkgs.linuxPackages_cachyos;
  };
}
```

This stops working if I try to use `linuxPackages_cachyos-lto` instead. As more evidence this is a coincidence, using `pkgs.zfs` doesn't work because it's marked as broken with kernel 6.10.7, but using `pkgs.zfs_unstable` works.

**Comment by PedroHLC** [comment]
You don't need the userspace to be built with LLVM+LTO (only the kernel module needs to match the kernel's build environment), but it needs to match the same source:
```
{
  boot.zfs.package = pkgs.zfs_unstable.overrideAttrs (prevAttrs: {
    inherit (pkgs.linuxPackages_cachyos-lto.zfs_cachyos) src;
    patches = [ ];
    passthru = prevAttrs.passthru // {
      kernelModuleAttribute = "zfs_cachyos";
    };
  });
}
```

**Comment by magneticflux-** [comment]
This still fails to build with the same error:
```
> checking whether access_ok() has 'type' parameter... no
> checking whether global_node_page_state() exists... yes
> checking whether global_zone_page_state() exists... yes
> checking whether enum node_stat_item contains NR_FILE_PAGES... no
> checking whether enum node_stat_item contains NR_INACTIVE_ANON... no
> checking whether enum node_stat_item contains NR_INACTIVE_FILE... no
> checking whether enum zone_stat_item contains NR_FILE_PAGES... no
> checking whether enum zone_stat_item contains NR_INACTIVE_ANON... no
> checking whether enum zone_stat_item contains NR_INACTIVE_FILE... no
> checking whether global_page_state enums are sane... no
> NR_FILE_PAGES in either node_stat_item or zone_stat_item: NOT FOUND
> configure: error:
>         *** None of the expected "global page state" interfaces were detected.
>         *** This may be because your kernel version is newer than what is
>         *** supported, or you are using a patched custom kernel with
>         *** incompatible modifications.
>         ***
>         *** ZFS Version: zfs-2.2.4-1
>         *** Compatible Kernels: 3.10 - 6.8
```

I don't know where it's getting the ZFS version `2.2.4` from, but that's definitely what it's trying to build: I used `nix repl` to load my flake and navigated to `outputs.nixosConfigurations.{my-machine}.pkgs.zfs_cachyos.src.outPath` and the `META` file in the sources indicates it's 2.2.4.

**Comment by magneticflux-** [comment]
I followed the trail backwards and realized that the ZFS version in `versions.json` hasn't been updated, and followed _that_ back to the definitive source: https://github.com/CachyOS/linux-cachyos/blob/49b42b99f95657db708a89b7408556e1afa09e5a/linux-cachyos/PKGBUILD#L218 which _also_ isn't updated! How was this ever working at all???

**Comment by PedroHLC** [comment]
> which _also_ isn't updated! How was this ever working at all???

I tested it once (I use ZFS), months ago, it worked, and I never tried again. Other users of the repo seem to be only using `xone`. I think right now, we don't even have NVIDIA users using LTO.

Anyway, if the kernel module is also broken (I'm almost sure it is), then you can try to fix the stdenv at `pkgs/linux-cachyos/lib/llvm-module-overlay.nix`.

**Comment by magneticflux-** [comment]
~~I think the main problem is that `zfs_cachyos` expects to be built in-tree? Maybe? This is what the CachyOS PKGBUILD doesto it: https://github.com/CachyOS/linux-cachyos/blob/49b42b99f95657db708a89b7408556e1afa09e5a/linux-cachyos/PKGBUILD#L577-L590~~

Nevermind! To build ZFS into the kernel itself, you have to use its `--enable-linux-builtin` configure flag, then run their `copy-builtin` script to copy the object file Kconfig changes to the kernel sources. _Then_, build the kernel normally, but with the `CONFIG_ZFS=y` option! CachyOS doesn't do any of this, it just builds the regular module.

Unfortunately, there's still a mystery with that module: I went to CachyOS's repository and downloaded the kernel that includes ZFS (https://mirror.cachyos.org/repo/x86_64/cachyos/linux-cachyos-zfs-6.10.7-1-x86_64.pkg.tar.zst), unzipped it and the kernel object, ran `strings linux-cachyos-zfs-6.10.7-1-x86_64.pkg/usr/lib/modules/6.10.7-1-cachyos/zfs.ko | sort | uniq | grep "version"`, and saw `version=2.2.4-1`, so I have _no idea_ how that was built :rofl:

I hope this investigation helps the next person, but I think I'll stick to the normal kernel for now.

**Comment by ptr1337** [comment]
Im really unsure currently. We are actually using a custom branch, to provide compatibility for our zfs modules, see:
https://github.com/CachyOS/zfs/commits/6.11/

It has exposed as version, because I did not updated the tag. I have updated now to the latest zfs version our branch, see here:
https://github.com/CachyOS/zfs/commits/zfs-2.2.6-cachyos

This will be used with the upcoming kernel update.

There is no need to use --enable-builtin. This makes massive issues, when building with Clang or equal. The module generally builds, but the complete boot freezes and crashes, therefore we are not using --enable-builtin.

You can find our PKGBUILDs here:
1. used commit to build: https://github.com/CachyOS/linux-cachyos/blob/master/linux-cachyos/PKGBUILD#L218
2. Building of the module: https://github.com/CachyOS/linux-cachyos/blob/master/linux-cachyos/PKGBUILD#L577-L590
3. Packaging: https://github.com/CachyOS/linux-cachyos/blob/master/linux-cachyos/PKGBUILD#L716-L729

We are having quite many users on CachyOS, which are using zfs OOB and there are no issues with the building neither. Likely, you should just follow the Building/Packaging as we do.

**Comment by PedroHLC** [comment]
Currently, I don't have time to deal with -LTO's kernel modules. Building all the modules for all the other kernels is all I have time to do. Thankfully, the kernel itself works.

I added a note in the README/website: https://github.com/chaotic-cx/nyx/commit/d5c5d1bd9f8485354f0b463d13a844997189acf1

Closing this, but if someone has time and is able to fix it, please submit a PR.
