### ISSUE TITLE
linux-cachyos: Scheduler not enabled by default

### ISSUE THREAD

**Issue by brenix** [chaotic-cx/nyx#98]
First of all, thank you for this flake! 

I started using the `linuxPackages_cachyos` kernel. It seems that recently, the BORE scheduler is no longer enabled in the kernel config:

```
$ zgrep BORE /proc/config.gz
# CONFIG_SCHED_BORE is not set

$ sysctl kernel.sched_bore
sysctl: cannot stat /proc/sys/kernel/sched_bore: No such file or directory
```

My understanding is that the sysctl listed above should exist if the BORE scheduler is enabled. However I'm a bit confused as the patch defaults to `Y` [here](https://github.com/CachyOS/kernel-patches/blob/master/6.3/sched/0001-bore-cachy.patch#L54)

Though it seems that the upstream cachyos PKGBUILDs are enabling this kernel config [here](https://github.com/CachyOS/linux-cachyos/blob/master/linux-cachyos/PKGBUILD#L335) when building the package (e.g makepkg). 

I think the same needs to be done in the nix derivation somehow, and possibly other common config options too. The upstream patches used do not seem to do this by default.

This appears it may have stopped working after moving to `linuxManualConfig` in this PR: https://github.com/chaotic-cx/nyx/pull/76

**Comment by PedroHLC** [comment]
@dr460nf1r3 seems like we shouldn't have dropped the extraConfig after adding the configfile, ptr1337 told us they were defining some in the pkgbuild, and I forgot, do you remember?

**Comment by dr460nf1r3** [comment]
Oh boy. The reason I removed it is mainly that there is no `extraConfig` when using `manualBuild` - if you know how to add this back it'll be great! https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/kernel/manual-config.nix

Thankfully we have git versioning :yum:

https://github.com/chaotic-cx/nyx/blob/01962a3969bbc99e70f085c8bb2915bf6f95df3e/pkgs/linux-cachyos/default.nix#L59

**Comment by brenix** [comment]
Thanks for taking a look into this, I see the referenced PR. While tinkering I came across this, which I found interesting but may provide some helpful context if needed: https://github.com/VolodiaPG/nur-packages/tree/master/pkgs/linux-cachyos

**Comment by PedroHLC** [comment]
That's the first one we based it of. But ptr1337 (cachyos founder) found it lacking most of his tweaks in config, and we've been trying to pull them since then.

**Comment by dr460nf1r3** [comment]
> My understanding is that the sysctl listed above should exist if the BORE scheduler is enabled. However I'm a bit confused as the patch defaults to `Y` [here](https://github.com/CachyOS/kernel-patches/blob/master/6.3/sched/0001-bore-cachy.patch?rgh-link-date=2023-05-12T17%3A35%3A48Z#L54)

Thinking about it does make sense. The patches are applied before the config is derived from the upstream repo, so any changes done to the config are overwritten. The PR will luckily solve this. I also ensured we are in fact setting all options from the PKGBUILD defaults by comparing current values to the desired ones, @PedroHLC needs to add those and we will be ready to merge it :yum:

**Comment by PedroHLC** [comment]
```
nix-repl> nixosConfigurations.laptop.config.boot.kernelPackages.kernel.config.CONFIG_SCHED_BORE
{ optional = false; tristate = "y"; }
```

```
╰─λ zgrep 'BORE' /proc/config.gz
# CONFIG_SCHED_BORE is not set
```

Magic stuff is complicated

**Comment by brenix** [comment]
Confirmed working now after changes from #104. Thanks!

**Comment by fproverbio** [comment]
sorry to comment on a closed issue, i was investigating why i couldn't enable BORE on linux-cachyos and stumbled upon this thread. unfortunately the merged fix doesn't seem to be working for me on a recent install of chaotic-nyx (done yesterday).
How can i troubleshoot this? i'm very new to nix in general.

kernel kconfig doesn't have the BORE option:

`[user@neuromancer:~]$ zgrep BORE /proc/config.gz`
`nothing`

and sched_bore doesn't indeed exist:

`[user@neuromancer:~]$ sysctl kernel.sched_bore`
`sysctl: cannot stat /proc/sys/kernel/sched_bore: No such file or directory`
